/**
 * Task Execution Skill - Entry Point
 * 
 * This module provides the core functionality for the Task Execution Skill.
 * It takes task plans generated by the Task Planning Skill and executes the steps contained within them.
 */

export interface TaskStep {
  stepId: string;
  description: string;
  action: string;
  parameters: Record<string, any>;
  dependencies: string[];
  optional: boolean;
  estimatedDurationMs?: number;
}

export interface TaskPlan {
  planId: string;
  intentType: string;
  steps: TaskStep[];
  createdAt: Date;
  valid: boolean;
  validationErrors: string[];
}

export interface StepResult {
  stepId: string;
  status: 'success' | 'failure' | 'skipped';
  executedAt: Date;
  durationMs: number;
  output?: Record<string, any>;
  error?: string;
  retryCount: number;
}

export interface ExecutionResult {
  executionId: string;
  planId: string;
  status: 'success' | 'partial_failure' | 'failure';
  startedAt: Date;
  completedAt: Date;
  stepResults: StepResult[];
  totalSteps: number;
  successfulSteps: number;
  failedSteps: number;
  executionErrors: string[];
  executionStats: Record<string, any>;
  performanceMetrics: Record<string, number>;
  securityValidationPassed: boolean;
}

export interface SecurityPolicy {
  policyId: string;
  name: string;
  allowedActions: string[];
  blockedActions: string[];
  conditions: Record<string, any>;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Main function to execute a task plan
 */
export async function executeTaskPlan(taskPlan: TaskPlan, securityPolicy: SecurityPolicy): Promise<ExecutionResult> {
  const startTime = Date.now();
  const executionId = `exec-${Date.now()}`;
  
  // Validate the task plan against security policy
  const validationResult = validateTaskPlanAgainstPolicy(taskPlan, securityPolicy);
  
  if (!validationResult.isValid) {
    // If the plan contains blocked actions, return an error result
    const stepResults: StepResult[] = taskPlan.steps.map(step => ({
      stepId: step.stepId,
      status: 'failure',
      executedAt: new Date(),
      durationMs: 0,
      error: `Action '${step.action}' is not allowed: ${validationResult.errors.join(', ')}`,
      retryCount: 0
    }));
    
    return {
      executionId,
      planId: taskPlan.planId,
      status: 'failure',
      startedAt: new Date(startTime),
      completedAt: new Date(),
      stepResults,
      totalSteps: taskPlan.steps.length,
      successfulSteps: 0,
      failedSteps: taskPlan.steps.length,
      executionErrors: validationResult.errors,
      executionStats: {},
      performanceMetrics: {},
      securityValidationPassed: false
    };
  }
  
  // Execute steps respecting dependencies
  const stepResults = await executeStepsWithDependencies(taskPlan.steps);
  
  // Calculate execution statistics
  const successfulSteps = stepResults.filter(sr => sr.status === 'success').length;
  const failedSteps = stepResults.filter(sr => sr.status === 'failure').length;
  
  // Determine overall status
  const status = failedSteps === 0 ? 'success' : (successfulSteps > 0 ? 'partial_failure' : 'failure');
  
  return {
    executionId,
    planId: taskPlan.planId,
    status,
    startedAt: new Date(startTime),
    completedAt: new Date(),
    stepResults,
    totalSteps: taskPlan.steps.length,
    successfulSteps,
    failedSteps,
    executionErrors: [],
    executionStats: {
      averageStepDurationMs: stepResults.reduce((sum, sr) => sum + sr.durationMs, 0) / stepResults.length || 0,
      totalExecutionDurationMs: Date.now() - startTime
    },
    performanceMetrics: stepResults.reduce((metrics, sr) => {
      metrics[sr.stepId] = sr.durationMs;
      return metrics;
    }, {} as Record<string, number>),
    securityValidationPassed: true
  };
}

/**
 * Validate a task plan against a security policy
 */
function validateTaskPlanAgainstPolicy(taskPlan: TaskPlan, securityPolicy: SecurityPolicy): { isValid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  for (const step of taskPlan.steps) {
    // Check if action is in blocked actions
    if (securityPolicy.blockedActions.includes(step.action)) {
      errors.push(`Action '${step.action}' is explicitly blocked by security policy`);
      continue;
    }
    
    // Check if action is in allowed actions (if allowed actions list is not empty)
    if (securityPolicy.allowedActions.length > 0 && !securityPolicy.allowedActions.includes(step.action)) {
      errors.push(`Action '${step.action}' is not in the allowed actions list`);
    }
  }
  
  return {
    isValid: errors.length === 0,
    errors
  };
}

/**
 * Execute steps respecting dependencies
 */
async function executeStepsWithDependencies(steps: TaskStep[]): Promise<StepResult[]> {
  // Create a mapping of stepId to step for easy lookup
  const stepMap = new Map(steps.map(step => [step.stepId, step]));
  
  // Track which steps are ready to execute (no unmet dependencies)
  const readySteps: TaskStep[] = [];
  const stepStatus = new Map<string, 'pending' | 'ready' | 'executing' | 'completed' | 'failed'>(); // Tracks status of each step
  
  // Initialize all steps as pending
  for (const step of steps) {
    stepStatus.set(step.stepId, 'pending');
  }
  
  // Initially, add steps with no dependencies to ready queue
  for (const step of steps) {
    if (step.dependencies.length === 0) { // No dependencies
      stepStatus.set(step.stepId, 'ready');
      readySteps.push(step);
    }
  }
  
  const stepResults: StepResult[] = [];
  
  // Process steps until all are completed
  while (Array.from(stepStatus.values()).some(status => ['pending', 'ready', 'executing'].includes(status))) {
    // Execute all currently ready steps in parallel
    const currentBatch = [...readySteps]; // Copy array to safely modify original
    for (const step of readySteps) {
      if (stepStatus.get(step.stepId) === 'ready') {
        currentBatch.push(step);
        readySteps.splice(readySteps.indexOf(step), 1); // Remove from ready queue
        stepStatus.set(step.stepId, 'executing');
      }
    }
    
    if (currentBatch.length === 0) {
      // No ready steps but not all steps completed - check for circular dependencies
      const pendingSteps = Array.from(stepStatus.entries())
        .filter(([_, status]) => status === 'pending')
        .map(([stepId, _]) => stepId);
      
      if (pendingSteps.length > 0) {
        // Check if dependencies are impossible to satisfy
        for (const stepId of pendingSteps) {
          const step = stepMap.get(stepId)!;
          const unmetDeps = step.dependencies.filter(dep => stepStatus.get(dep) !== 'completed');
          if (unmetDeps.length > 0) {
            // Add error for unmet dependencies
            stepResults.push({
              stepId,
              status: 'failure',
              executedAt: new Date(),
              durationMs: 0,
              error: `Unmet dependencies: ${unmetDeps.join(', ')}`,
              retryCount: 0
            });
            stepStatus.set(stepId, 'failed');
          }
        }
      }
      
      // If still no ready steps, break to avoid infinite loop
      if (!Array.from(stepStatus.values()).some(status => status === 'executing')) {
        break;
      }
      
      // Otherwise, continue to let executing steps finish
      await new Promise(resolve => setTimeout(resolve, 10)); // Small delay to prevent busy waiting
      continue;
    }
    
    // Execute the current batch of steps
    const batchResults = await executeBatch(currentBatch);
    stepResults.push(...batchResults);
    
    // Update status for completed steps and check for newly ready steps
    for (const result of batchResults) {
      stepStatus.set(result.stepId, result.status === 'success' ? 'completed' : 'failed');
      
      // Check if any pending steps now have all dependencies met
      for (const [stepId, step] of stepMap.entries()) {
        if (stepStatus.get(stepId) === 'pending') {
          const unmetDeps = step.dependencies.filter(dep => stepStatus.get(dep) !== 'completed');
          if (unmetDeps.length === 0) { // All dependencies met
            stepStatus.set(stepId, 'ready');
            readySteps.push(step);
          }
        }
      }
    }
  }
  
  return stepResults;
}

/**
 * Execute a batch of steps in parallel
 */
async function executeBatch(steps: TaskStep[]): Promise<StepResult[]> {
  // Create tasks for parallel execution
  const tasks = steps.map(step => executeSingleStep(step));
  const results = await Promise.all(tasks);
  
  // Process results, handling any exceptions
  const stepResults: StepResult[] = [];
  for (let i = 0; i < results.length; i++) {
    const result = results[i];
    if (result instanceof Error) {
      stepResults.push({
        stepId: steps[i].stepId,
        status: 'failure',
        executedAt: new Date(),
        durationMs: 0,
        error: result.message,
        retryCount: 0
      });
    } else if (typeof result === 'object' && result !== null) {
      stepResults.push(result);
    } else {
      // Unexpected result type
      stepResults.push({
        stepId: steps[i].stepId,
        status: 'failure',
        executedAt: new Date(),
        durationMs: 0,
        error: `Unexpected result type: ${typeof result}`,
        retryCount: 0
      });
    }
  }
  
  return stepResults;
}

/**
 * Execute a single step
 */
async function executeSingleStep(step: TaskStep): Promise<StepResult> {
  const startTime = Date.now();
  
  try {
    // Simulate step execution based on action type
    // In a real implementation, this would call the appropriate action handler
    await performAction(step.action, step.parameters);
    
    const duration = Date.now() - startTime; // Convert to milliseconds
    
    return {
      stepId: step.stepId,
      status: 'success',
      executedAt: new Date(),
      durationMs: duration,
      output: {}, // Add actual output if needed
      retryCount: 0
    };
  } catch (error) {
    const duration = Date.now() - startTime; // Convert to milliseconds
    
    return {
      stepId: step.stepId,
      status: 'failure',
      executedAt: new Date(),
      durationMs: duration,
      error: error instanceof Error ? error.message : String(error),
      retryCount: 0
    };
  }
}

/**
 * Perform the specified action with the given parameters
 */
async function performAction(action: string, parameters: Record<string, any>): Promise<void> {
  // This is a simulation - in a real implementation, this would call
  // the appropriate action handler based on the action type
  await new Promise(resolve => setTimeout(resolve, 10)); // Simulate some processing time
  
  // Example action handling (would be expanded in real implementation)
  switch (action) {
    case "validate_params":
      // Validate parameters based on requirements
      const requiredFields = parameters.required_fields || [];
      for (const field of requiredFields) {
        if (!(field in parameters.params)) {
          throw new Error(`Missing required field: ${field}`);
        }
      }
      break;
    case "create_record":
      // Create a record in the database
      const table = parameters.table;
      const data = parameters.data;
      if (!table || !data) {
        throw new Error("Missing table or data for create_record action");
      }
      break;
    case "update_record":
      // Update a record in the database
      const recordId = parameters.record_id;
      const updates = parameters.updates;
      if (!recordId || !updates) {
        throw new Error("Missing record_id or updates for update_record action");
      }
      break;
    case "delete_record":
      // Delete a record from the database
      const delRecordId = parameters.record_id;
      if (!delRecordId) {
        throw new Error("Missing record_id for delete_record action");
      }
      break;
    default:
      // Unknown action
      throw new Error(`Unknown action: ${action}`);
  }
}

// Export the skill interface
export default {
  executeTaskPlan,
  validateTaskPlanAgainstPolicy
};