[build]
  base = "phase2/frontend"
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_BASE_URL = "https://sehrkhan873-hakathon-2.hf.space"

[[plugins]]
  package = "@netlify/plugin-nextjs"
