headersOrigin = "inline"
redirectsOrigin = "inline"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\user\\Desktop\\hakathon_2\\phase2\\frontend\\.next"
publishOrigin = "ui"
commandOrigin = "config"
base = "C:\\Users\\user\\Desktop\\hakathon_2\\phase2\\frontend"
command = "npm install && npm run build"

[build.environment]
NODE_VERSION = "20"
NEXT_PUBLIC_API_BASE_URL = "https://sehrkhan873-hakathon-2.hf.space"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]